# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-09-12 12:43-0300\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: api_app/apps.py:327
msgid "Lista de agentes activos de un Grupo"
msgstr "Lista de agentes ativos de um Grupo"

#: api_app/apps.py:329
msgid "Campañas relacionadas a un supervisor"
msgstr "Campanhas relacionadas a um supervisor"

#: api_app/apps.py:331
msgid "Opciones de calificacion de una campaña (id campaña externo)"
msgstr "Opções de qualificação de uma campanha (ID de campanha externo)"

#: api_app/apps.py:334
msgid "Opciones de calificacion de una campaña (id campaña oml)"
msgstr "Opções de qualificação de uma campanha (ID da campanha OML)"

#: api_app/apps.py:337
msgid "Ver/editar calificación cliente"
msgstr "Ver/editar avaliação do cliente"

#: api_app/apps.py:339
msgid "Crear calificacion cliente"
msgstr "Criar avaliação do cliente"

#: api_app/apps.py:341
msgid "Crear contacto"
msgstr "Criar contato"

#: api_app/apps.py:343
msgid "Metadata de la base de datos de una campaña"
msgstr "Metadados da base de dados de uma campanha"

#: api_app/apps.py:345
msgid "Crear nuevo rol"
msgstr "Criar novo papel"

#: api_app/apps.py:347
msgid "Eliminar rol"
msgstr "Eliminar papel"

#: api_app/apps.py:349
msgid "Actualizar permisos de Rol"
msgstr "Atualizar permissões do papel"

#: api_app/apps.py:351
msgid "Devuelve información de los agentes en el sistema"
msgstr "Retorna informação dos agentes no sistema"

#: api_app/apps.py:354
msgid "Devuelve datos de usuario de los agentes"
msgstr "Devolve dados do usuário de um agente"

#: api_app/apps.py:357
msgid "Reporte de llamadas entrantes de supervisión."
msgstr "Relatório de chamadas recebidas de supervisão."

#: api_app/apps.py:359
msgid "Reporte de llamadas salientes no dialer de supervisión."
msgstr "Relatório de chamadas de saída não dialer de supervisão."

#: api_app/apps.py:363
msgid "Ejecuta acciones de supervisión sobre agente (Deslogueo, pausas, etc..)"
msgstr "Executa ações de supervisão sobre o agente (Desconexão, pausas, etc.)"

#: api_app/apps.py:366
msgid "Cantidades por tipos de llamada en una campaña"
msgstr "Quantidades por tipos de chamada em uma campanha"

#: api_app/apps.py:369
msgid "Cantidades por tipo de calificación en una campaña"
msgstr "Quantidades por tipo de qualificação em uma campanha"

#: api_app/apps.py:372
msgid "Reasignar una Agenda a otro Agente"
msgstr "Reatribuir uma Agenda para outro Agente"

#: api_app/apps.py:374
msgid "Información de contacto de una  Agenda"
msgstr "Informação de contato de uma Agenda"

#: api_app/apps.py:376
msgid "Exportar reporte de contactados de una campaña a csv"
msgstr "Exportar relatório de contatados de uma campanha para csv"

#: api_app/apps.py:379
msgid "Exportar reporte de calificados de una campaña a csv"
msgstr "Exportar relatório de qualificados de uma campanha para csv"

#: api_app/apps.py:382
msgid "Exportar reporte de no atendidos de una campaña a csv"
msgstr "Exportar relatório de não atendidos de uma campanha para csv"

#: api_app/apps.py:385 api_app/apps.py:388
msgid "Exportar reporte de calificaciones de una campaña a csv"
msgstr "Exportar relatório de avaliações de uma campanha para csv"

#: api_app/apps.py:391
msgid "API para exportar resultados de base contactados a csv"
msgstr "API para exportar resultados de base de contatados para csv"

#: api_app/apps.py:394
msgid "Contactos de una campaña"
msgstr "Contatos de uma campanha"

#: api_app/apps.py:396
msgid "Ejecuta un click 2 call a una campaña"
msgstr "Executa um clique para chamar em uma campanha"

#: api_app/apps.py:398
msgid "Ejecuta un click 2 call fuera de campaña"
msgstr "Executa um clique para chamar fora de campanha"

#: api_app/apps.py:400
msgid "Ejecuta un hangup call via AMI"
msgstr "Executa um hangup call via AMI"

#: api_app/apps.py:402
#, python-brace-format
msgid "Ejecuta el login del agente en {0}."
msgstr "Executa o login do agente no {0}."

#: api_app/apps.py:405
#, python-brace-format
msgid "Ejecuta el logout del agente en {0}"
msgstr "Executa o logout do agente no {0}"

#: api_app/apps.py:408
#, python-brace-format
msgid "Logout del agente en {0}"
msgstr "Logout do agente no {0}"

#: api_app/apps.py:410
msgid "Pone al agente en una pausa"
msgstr "Coloca o agente em uma pausa"

#: api_app/apps.py:412
msgid "Saca al agente de una pausa"
msgstr "Retira o agente de uma pausa"

#: api_app/apps.py:414
msgid "Establece el estado Ringing del Agente"
msgstr "Estabelece o estado de Chamando do Agente"

#: api_app/apps.py:416
msgid "Establece el estado Reject del Agente"
msgstr "Estabelece o estado de Rejeição do Agente"

#: api_app/apps.py:418
msgid "Establece el estado Disabled del Agente"
msgstr "Estabelece o estado Desabilitado do Agente"

#: api_app/apps.py:420
msgid "Devuelve credenciales SIP de un agente"
msgstr "Devolve credenciais SIP de um agente"

#: api_app/apps.py:422
msgid "Establece el estado de revisión de una Auditoría"
msgstr "Estabelece o estado de revisão de uma Auditoria"

#: api_app/apps.py:425
msgid "Almacena en la base de datos los contactos subidos en archivo csv"
msgstr "Armazena no banco de dados os contatos carregados em arquivo csv"

#: api_app/apps.py:428
msgid "Detecta si una llamada esta calificada."
msgstr "Detecta se uma chamada está qualificada."

#: api_app/apps.py:431
msgid "Reenvía la llave de la instancia registrada por email"
msgstr "Reenvia a chave da instância registrada por email"

#: api_app/apps.py:433
msgid "Retorna el archivo csv de auditoria"
msgstr "Retorna o arquivo csv de auditoria"

#: api_app/apps.py:436
msgid "Retorna el archivo de grabación especificado"
msgstr "Retorna o arquivo de gravação especificado"

#: api_app/apps.py:439
msgid "Retorna Zip con archivos de grabación especificados"
msgstr "Retorna Zip com arquivos de gravação especificados"

#: api_app/apps.py:442
msgid "Retorna URL del archivos de grabación asociado al callid"
msgstr "Retorna URL dos arquivos de gravação associados ao callid"

#: api_app/apps.py:445
msgid "Devuelve los contactos asignados de una campaña preview"
msgstr "Devolve os contatos atribuídos de uma campanha prévia"

#: api_app/apps.py:448
msgid "Loggea el evento hold o unhold"
msgstr "Registra o evento de retenção ou liberação"

#: api_app/apps.py:451
msgid "Lista de agentes para transferir llamadas"
msgstr "Lista de agentes para transferir chamadas"

#: api_app/apps.py:454
msgid "Lista audios de asterisk"
msgstr "Lista áudios do asterisk"

#: api_app/apps.py:457
msgid "Lista de grupos de agentes"
msgstr "Lista de grupos de agentes"

#: api_app/apps.py:460
msgid "Lista de Agentes"
msgstr "Lista de Agentes"

#: api_app/apps.py:463
msgid "Dashboard de supervision"
msgstr "Painel de supervisão"

#: api_app/apps.py:466
msgid "Auditoría a supervisores"
msgstr "Auditoria de supervisores"

#: api_app/apps.py:469
msgid "Listas de nombres de columnas para Base de datos de Contactos"
msgstr "Listas de nomes de colunas para Banco de dados de Contatos"

#: api_app/apps.py:472
#, python-brace-format
msgid "Reinicia servicio {0} Dialer"
msgstr "Reinicia serviço {0} Dialer"

#: api_app/apps.py:475
#, python-brace-format
msgid "Estado del servicio {0} Dialer"
msgstr "Estado do serviço {0} Dialer"

#: api_app/apps.py:478
msgid "Start servicio Dialer"
msgstr "Iniciar serviço Dialer"

#: api_app/apps.py:481
msgid "Stop servicio Dialer"
msgstr "Parar serviço Dialer"

#: api_app/apps.py:484
msgid "Lista de agentes por campaña"
msgstr "Lista de agentes por campanha"

#: api_app/apps.py:487
msgid "Actualiza los agentes de una campaña"
msgstr "Atualiza os agentes de uma campanha"

#: api_app/apps.py:490
msgid "Actualiza las campañas de un agente"
msgstr "Atualiza as campanhas de um agente"

#: api_app/apps.py:493
msgid "Obtiene todos los agentes activos"
msgstr "Obtém todos os agentes ativos"

#: api_app/apps.py:496
msgid "Obtiene las pausas que no estan eliminadas"
msgstr "Obtém as pausas que não estão eliminadas"

#: api_app/apps.py:499
msgid "Lista los conjuntos de pausas"
msgstr "Lista os conjuntos de pausas"

#: api_app/apps.py:502
msgid "Obtiene el detalle de un conjunto de pausas"
msgstr "Obtém o detalhe de um conjunto de pausas"

#: api_app/apps.py:505
msgid "Crea un conjunto de pausas"
msgstr "Cria um conjunto de pausas"

#: api_app/apps.py:508
msgid "Actualiza un conjunto de pausas"
msgstr "Atualiza um conjunto de pausas"

#: api_app/apps.py:511
msgid "Elimina un conjunto de pausas"
msgstr "Elimina um conjunto de pausas"

#: api_app/apps.py:514
msgid "Crea una configuracion de pausa"
msgstr "Cria uma configuração de pausa"

#: api_app/apps.py:517
msgid "Actualiza una configuracion de pausa"
msgstr "Atualiza uma configuração de pausa"

#: api_app/apps.py:520
msgid "Elimina una configuracion de pausa"
msgstr "Elimina uma configuração de pausa"

#: api_app/apps.py:523
msgid "Lista los sitios externos"
msgstr "Lista os sites externos"

#: api_app/apps.py:526
msgid "Obtiene el detalle de un sitio externo"
msgstr "Obtém o detalhe de um site externo"

#: api_app/apps.py:529
msgid "Crea un sitio externo"
msgstr "Cria um site externo"

#: api_app/apps.py:532
msgid "Actualiza un sitio externo"
msgstr "Atualiza um site externo"

#: api_app/apps.py:535
msgid "Elimina un sitio externo"
msgstr "Elimina um site externo"

#: api_app/apps.py:538
msgid "Lista las autenticaciones para sitios externos"
msgstr "Lista as autenticações para sites externos"

#: api_app/apps.py:541
msgid "Obtiene el detalle de una autenticacion para sitio externo"
msgstr "Obtém o detalhe de uma autenticação para site externo"

#: api_app/apps.py:544
msgid "Crea una autenticacion para sitio externo"
msgstr "Cria uma autenticação para site externo"

#: api_app/apps.py:547
msgid "Prueba la autenticacion para sitio externo"
msgstr "Evalúa uma autenticação para site externo"

#: api_app/apps.py:550
msgid "Actualiza una autenticacion para sitio externo"
msgstr "Atualiza uma autenticação para site externo"

#: api_app/apps.py:553
msgid "Elimina una autenticacion para sitio externo"
msgstr "Elimina uma autenticação para site externo"

#: api_app/apps.py:556
msgid "Oculta un sitio externo"
msgstr "Oculta um site externo"

#: api_app/apps.py:559
msgid "Desoculta un sitio externo"
msgstr "Revela um site externo"

#: api_app/apps.py:562
msgid "Lista las calificaciones"
msgstr "Lista as qualificações"

#: api_app/apps.py:565
msgid "Crea una calificacion"
msgstr "Cria uma qualificação"

#: api_app/apps.py:568
msgid "Actualiza una calificacion"
msgstr "Atualiza uma qualificação"

#: api_app/apps.py:571
msgid "Elimina una calificacion"
msgstr "Elimina uma qualificação"

#: api_app/apps.py:574
msgid "Obtiene detalle de una calificacion"
msgstr "Obtém detalhe de uma qualificação"

#: api_app/apps.py:577
msgid "Lista los destinos entrantes"
msgstr "Lista os destinos de entrada"

#: api_app/apps.py:580
msgid "Lista tipos de destinos entrantes"
msgstr "Lista tipos de destinos de entrada"

#: api_app/apps.py:583
msgid "Lista los sistemas externos"
msgstr "Lista os sistemas externos"

#: api_app/apps.py:586
msgid "Crea un sistema externo"
msgstr "Cria um sistema externo"

#: api_app/apps.py:589
msgid "Actualiza un sistema externo"
msgstr "Atualiza um sistema externo"

#: api_app/apps.py:592
msgid "Obtiene detalle de un sistema externo"
msgstr "Obtém detalhe de um sistema externo"

#: api_app/apps.py:595
msgid "Obtiene los agentes para asignar a un sistema externo"
msgstr "Obtém os agentes para atribuir a um sistema externo"

#: api_app/apps.py:598
msgid "Lista los formularios"
msgstr "Lista os formulários"

#: api_app/apps.py:601
msgid "Crea un formulario"
msgstr "Cria um formulário"

#: api_app/apps.py:604
msgid "Actualiza un formulario"
msgstr "Atualiza um formulário"

#: api_app/apps.py:607
msgid "Obtiene detalle de un formulario"
msgstr "Obtém detalhe de um formulário"

#: api_app/apps.py:610
msgid "Elimina un formulario"
msgstr "Elimina um formulário"

#: api_app/apps.py:613
msgid "Oculta un formulario"
msgstr "Oculta um formulário"

#: api_app/apps.py:616
msgid "Desoculta un formulario"
msgstr "Revela um formulário"

#: api_app/apps.py:619
msgid "Lista las pausas"
msgstr "Lista as pausas"

#: api_app/apps.py:622
msgid "Crea una pausa"
msgstr "Cria uma pausa"

#: api_app/apps.py:625
msgid "Actualiza una pausa"
msgstr "Atualiza uma pausa"

#: api_app/apps.py:628
msgid "Obtiene detalle de una pausa"
msgstr "Obtém detalhe de uma pausa"

#: api_app/apps.py:631
msgid "Elimina una pausa"
msgstr "Elimina uma pausa"

#: api_app/apps.py:634
msgid "Reactiva una pausa"
msgstr "Reativa uma pausa"

#: api_app/apps.py:637
msgid "Lista las rutas entrantes"
msgstr "Lista as rotas de entrada"

#: api_app/apps.py:640
msgid "Crea una ruta entrante"
msgstr "Cria uma rota de entrada"

#: api_app/apps.py:643
msgid "Actualiza una ruta entrante"
msgstr "Atualiza uma rota de entrada"

#: api_app/apps.py:646
msgid "Obtiene detalle de una ruta entrante"
msgstr "Obtém detalhe de uma rota de entrada"

#: api_app/apps.py:649
msgid "Elimina una ruta entrante"
msgstr "Elimina uma rota de entrada"

#: api_app/apps.py:652
msgid "Obtiene los destinos disponibles"
msgstr "Obtém os destinos disponíveis"

#: api_app/apps.py:655
msgid "Lista las rutas salientes"
msgstr "Lista as rotas de saída"

#: api_app/apps.py:658
msgid "Crea una ruta saliente"
msgstr "Cria uma rota de saída"

#: api_app/apps.py:661
msgid "Actualiza una ruta saliente"
msgstr "Atualiza uma rota de saída"

#: api_app/apps.py:664
msgid "Obtiene detalle de una ruta saliente"
msgstr "Obtém detalhe de uma rota de saída"

#: api_app/apps.py:667
msgid "Elimina una ruta saliente"
msgstr "Elimina uma rota de saída"

#: api_app/apps.py:670
msgid "Obtiene las troncales sip para rutas salientes"
msgstr "Obtém as troncos SIP para rotas de saída"

#: api_app/apps.py:673
msgid "Obtiene las troncales huerfanas de una ruta saliente"
msgstr "Obtém as troncos órfãs de uma rota de saída"

#: api_app/apps.py:676
msgid "Reordena las rutas salientes"
msgstr "Reorganiza as rotas de saída"

#: api_app/apps.py:679
msgid "Lista los grupos horarios"
msgstr "Lista os grupos horários"

#: api_app/apps.py:682
msgid "Crea un grupo horario"
msgstr "Cria um grupo horário"

#: api_app/apps.py:685
msgid "Actualiza un grupo horario"
msgstr "Atualiza um grupo horário"

#: api_app/apps.py:688
msgid "Obtiene detalle de un grupo horario"
msgstr "Obtém detalhe de um grupo horário"

#: api_app/apps.py:691
msgid "Elimina un grupo horario"
msgstr "Elimina um grupo horário"

#: api_app/apps.py:694
msgid "Lista los ivrs"
msgstr "Lista os IVRs"

#: api_app/apps.py:697
msgid "Crea un ivr"
msgstr "Cria um IVR"

#: api_app/apps.py:700
msgid "Actualiza un ivr"
msgstr "Atualiza um IVR"

#: api_app/apps.py:703
msgid "Obtiene detalle de un ivr"
msgstr "Obtém detalhe de um IVR"

#: api_app/apps.py:706
msgid "Elimina un ivr"
msgstr "Elimina um IVR"

#: api_app/apps.py:709
msgid "Obtiene los audios disponibles para ivr"
msgstr "Obtém os áudios disponíveis para IVR"

#: api_app/apps.py:712
msgid "Obtiene los destinos por tipo para un ivr"
msgstr "Obtém os destinos por tipo para um IVR"

#: api_app/apps.py:715
msgid "Obtener el detalle del registro de la instancia"
msgstr "Obtém o detalhe do registro da instância"

#: api_app/apps.py:718
msgid "Registrar la instancia"
msgstr "Registra a instância"

#: api_app/apps.py:721
msgid "Crear una base de datos de contactos"
msgstr "Criar o banco de dados de contato"

#: api_app/apps.py:724
msgid "Crear un contacto para una base de datos de contactos"
msgstr "Criar um contato para um banco de dados de contatos"

#: api_app/apps.py:727
msgid "Campañas asociadas a una base de datos de contactos"
msgstr "Campanhas associadas a um banco de dados de contatos"

#: api_app/apps.py:730
msgid "Loguea un intento de transferencia a Survey"
msgstr "Registra uma tentativa de transferência para Pesquisa"

#: api_app/apps.py:733
msgid "Obtener la cantidad de agentes de una campaña en cada estado"
msgstr "Obter quantia de agentes de uma campanha em cada estado"

#: api_app/apps.py:736
msgid "Obtener la lista de agentes de una campaña con su estado"
msgstr "Obter lista de agentes de uma campanha com seu estado"

#: api_app/apps.py:739
msgid "Obtener la cantidad de llamadas Atendidas, Abandonadas, Expiradas"
msgstr "Obter a quantia de chamadas Atendidas, Abandonadas ou expiradas"

#: api_app/apps.py:742
msgid "Notificar que la llamada transferida ha finalizado"
msgstr "Notificar a finalização da chamada transferida"

#: api_app/forms.py:52 api_app/forms.py:97
#: api_app/tests/tests_api_click2call.py:135
#: api_app/tests/tests_api_click2call.py:207
msgid "El agente no participa en la campaña."
msgstr "O agente não participa da campanha."

#: api_app/forms.py:61 api_app/tests/tests_api_click2call.py:143
msgid "El contacto no corresponde a la campaña."
msgstr "O contato não corresponde à campanha."

#: api_app/forms.py:99 api_app/tests/tests_api_click2call.py:173
#: api_app/tests/tests_api_click2call.py:195
msgid "El agente no corresponde al sistema externo."
msgstr "O agente não corresponde ao sistema externo."

#: api_app/serializers/register_server.py:40
msgid "No tiene settings de conexion configurados"
msgstr "Não possui configurações de conexão definidas"

#: api_app/serializers/register_server.py:44 api_app/views/administrador.py:280
#, python-brace-format
msgid "Error en el intento de conexion a: {0} debido {1}"
msgstr "Erro na tentativa de conexão com: {0} devido a {1}"

#: api_app/serializers/reportes.py:44
msgid "Addon no instalado"
msgstr "Addon não instalado"

#: api_app/serializers/reportes.py:50
msgid "Parámetro requerido"
msgstr "Parâmetro requerido"

#: api_app/serializers/reportes.py:56
msgid "No existe una encuesta para esa campaña"
msgstr "Não existe uma pesquisa para essa campanha"

#: api_app/services/base_datos_contacto_service.py:44
#: api_app/views/base_de_contactos.py:295
msgid "Ya existe una base de datos de contactos con ese nombre"
msgstr "Já existe um banco de dados de contatos com esse nome"

#: api_app/services/base_datos_contacto_service.py:48
msgid ""
"El archivo especificado para realizar la importación de contactos no es "
"válido."
msgstr "O arquivo especificado para a importação de contatos não é válido."

#: api_app/services/base_datos_contacto_service.py:53
#: api_app/tests/tests_api_subir_base_contactos.py:208
#: api_app/views/administrador.py:194
msgid "El archivo a procesar tiene nombres de columnas repetidos."
msgstr "O arquivo a ser processado tem nomes de colunas repetidos."

#: api_app/services/base_datos_contacto_service.py:131
msgid "Archivo excede máximo de filas permitidas"
msgstr "Arquivo excede o máximo de linhas permitidas"

#: api_app/services/base_datos_contacto_service.py:135
msgid "Error al parsear el archivo csv"
msgstr "Erro ao analisar o arquivo CSV"

#: api_app/tests/campaign/agents/tests_add_agents_to_campaign.py:97
#: api_app/tests/campaign/agents/tests_add_agents_to_campaign.py:107
#: api_app/views/campaigns/add_agents_to_campaign.py:46
#: api_app/views/campaigns/add_agents_to_campaign.py:221
#: api_app/views/external_system.py:173
msgid "Se obtuvieron los agentes de forma exitosa"
msgstr "Os agentes foram obtidos com sucesso"

#: api_app/tests/campaign/agents/tests_add_agents_to_campaign.py:126
#: api_app/views/campaigns/add_agents_to_campaign.py:92
msgid "Se agregaron los agentes de forma exitosa a la campaña"
msgstr "Os agentes foram adicionados com sucesso à campanha"

#: api_app/tests/pause_sets/tests_configuraciones_de_pausas.py:69
#: api_app/views/pause_set.py:232
msgid "Se creo la configuracion de pausa de forma exitosa"
msgstr "A configuração de pausa foi criada com sucesso"

#: api_app/tests/pause_sets/tests_configuraciones_de_pausas.py:87
#: api_app/views/pause_set.py:312
msgid "Se actualizo la configuracion de pausa de forma exitosa"
msgstr "A configuração de pausa foi atualizada com sucesso"

#: api_app/tests/pause_sets/tests_configuraciones_de_pausas.py:105
#: api_app/views/pause_set.py:279
msgid "Se elimino la configuracion de pausa de forma exitosa"
msgstr "A configuração de pausa foi eliminada com sucesso"

#: api_app/tests/pause_sets/tests_configuraciones_de_pausas.py:124
#: api_app/views/pause_set.py:239
msgid "El timeout debe ser mayor a cero"
msgstr "O tempo de espera deve ser maior que zero"

#: api_app/tests/pause_sets/tests_configuraciones_de_pausas.py:136
#: api_app/views/pause_set.py:287
msgid "No puedes dejar a un Conjunto de Pausas vacio"
msgstr "Não é possível deixar um Conjunto de Pausas vazio"

#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:66
#: api_app/views/pause_set.py:69
msgid "Se obtuvieron los conjuntos de pausas de forma exitosa"
msgstr "Os conjuntos de pausas foram obtidos com sucesso"

#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:88
#: api_app/views/pause_set.py:128
msgid "Se creo el conjunto de pausa de forma exitosa"
msgstr "O conjunto de pausas foi criado com sucesso"

#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:109
#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:160
#: api_app/views/pause_set.py:133 api_app/views/pause_set.py:169
msgid "El nombre del conjunto es requerido"
msgstr "O nome do conjunto é necessário"

#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:125
#: api_app/views/pause_set.py:137
msgid "Debe existir al menos una pausa en el conjunto"
msgstr "Deve existir pelo menos uma pausa no conjunto"

#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:143
#: api_app/views/pause_set.py:165
msgid "Se actualizo el conjunto de pausa de forma exitosa"
msgstr "O conjunto de pausas foi atualizado com sucesso"

#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:172
#: api_app/views/pause_set.py:198
msgid "Se elimino el conjunto de pausa de forma exitosa"
msgstr "O conjunto de pausas foi eliminado com sucesso"

#: api_app/tests/pause_sets/tests_conjuntos_de_pausa.py:186
#: api_app/views/pause_set.py:205
msgid ""
"No puedes borrar un conjunto de pausas que esta asignado a un grupo de "
"agentes"
msgstr ""
"Não é possível apagar um conjunto de pausas que está atribuído a um grupo de "
"agentes"

#: api_app/tests/tests_api_call_dispositions.py:57
#: api_app/views/call_disposition.py:43
msgid "Se obtuvieron las calificaciones de forma exitosa"
msgstr "As qualificações foram obtidas com sucesso"

#: api_app/tests/tests_api_call_dispositions.py:76
#: api_app/views/call_disposition.py:112
msgid "Se creo la calificacion de forma exitosa"
msgstr "A qualificação foi criada com sucesso"

#: api_app/tests/tests_api_call_dispositions.py:92
#: api_app/views/call_disposition.py:120 api_app/views/call_disposition.py:164
msgid "Error al hacer la peticion"
msgstr "Erro ao fazer a solicitação"

#: api_app/tests/tests_api_call_dispositions.py:112
#: api_app/views/call_disposition.py:155
msgid "Se actualizo la calificacion de forma exitosa"
msgstr "A qualificação foi atualizada com sucesso"

#: api_app/tests/tests_api_call_dispositions.py:128
#: api_app/views/call_disposition.py:195
msgid "Se elimino la calificacion de forma exitosa"
msgstr "A qualificação foi eliminada com sucesso"

#: api_app/tests/tests_api_click2call.py:104
#: api_app/tests/tests_api_click2call.py:112
#: api_app/tests/tests_api_click2call.py:120
#: api_app/tests/tests_api_click2call.py:165
msgid "Escoja una opción válida. Esa opción no está entre las disponibles."
msgstr "Escolha uma opção válida. Essa opção não está entre as disponíveis."

#: api_app/tests/tests_api_click2call.py:157
#: api_app/tests/tests_api_contactos.py:169
#: api_app/tests/tests_api_contactos.py:261 api_app/views/agente.py:230
#: api_app/views/base_de_contactos.py:91 api_app/views/base_de_contactos.py:223
msgid "Sistema externo inexistente."
msgstr "Sistema externo inexistente."

#: api_app/tests/tests_api_contactos.py:113
#: api_app/views/base_de_contactos.py:180
msgid "Contacto agregado"
msgstr "Contato adicionado"

#: api_app/tests/tests_api_contactos.py:141
#: api_app/tests/tests_api_contactos.py:159
#: api_app/tests/tests_api_contactos.py:228
#: api_app/tests/tests_api_contactos.py:251
#: api_app/views/base_de_contactos.py:122
#: api_app/views/base_de_contactos.py:255
msgid "No tiene permiso para editar la campaña."
msgstr "Não tem permissão para editar a campanha."

#: api_app/tests/tests_api_contactos.py:177
#: api_app/tests/tests_api_contactos.py:194
#: api_app/tests/tests_api_contactos.py:271
#: api_app/tests/tests_api_contactos.py:291
#: api_app/views/base_de_contactos.py:115
#: api_app/views/base_de_contactos.py:248
msgid "Campaña inexistente."
msgstr "Campanha inexistente."

#: api_app/tests/tests_api_contactos.py:185
#: api_app/tests/tests_api_contactos.py:281
#: api_app/views/base_de_contactos.py:103
#: api_app/views/base_de_contactos.py:235
msgid "Debe indicar un idCampaign válido."
msgstr "Deve indicar um idCampaign válido."

#: api_app/tests/tests_api_contactos.py:301
msgid "Ya existe un contacto con ese id externo en la base de datos"
msgstr "Já existe um contato com esse id externo no banco de dados"

#: api_app/tests/tests_api_contactos.py:333
#: api_app/views/base_de_contactos.py:139
msgid "El campo es obligatorio"
msgstr "O campo é obrigatório"

#: api_app/tests/tests_api_contactos.py:344
#: api_app/views/base_de_contactos.py:131
msgid "Se recibieron campos incorrectos"
msgstr "Foram recebidos campos incorretos"

#: api_app/tests/tests_api_external_site_authentications.py:60
#: api_app/views/external_site_authentication.py:46
msgid "Se obtuvieron las autenticaciones para sitios externos de forma exitosa"
msgstr "As autenticações para sites externos foram obtidas com sucesso"

#: api_app/tests/tests_api_external_site_authentications.py:73
#: api_app/views/external_site_authentication.py:182
msgid ""
"Se obtuvo la informacion de la autenticacion para sitio externo de forma "
"exitosa"
msgstr ""
"A informação da autenticação para o site externo foi obtida com sucesso"

#: api_app/tests/tests_api_external_site_authentications.py:104
#: api_app/views/external_site_authentication.py:208
msgid "Se elimino la autenticacion para sitio externo de forma exitosa"
msgstr "A autenticação para site externo foi eliminada com sucesso"

#: api_app/tests/tests_api_external_site_authentications.py:120
#: api_app/views/external_site_authentication.py:214
msgid "No está permitido eliminar una autenticacion que tiene sitios externos"
msgstr "Não é permitido eliminar uma autenticação que possui sites externos"

#: api_app/tests/tests_api_external_site_authentications.py:147
#: api_app/views/external_site_authentication.py:73
msgid "Se creo la autenticacion para sitio externo de forma exitosa"
msgstr "A autenticação para site externo foi criada com sucesso"

#: api_app/tests/tests_api_external_sites.py:66
#: api_app/views/external_site.py:43
msgid "Se obtuvieron los sitios externos de forma exitosa"
msgstr "Os sites externos foram obtidos com sucesso"

#: api_app/tests/tests_api_external_sites.py:79
#: api_app/views/external_site.py:140
msgid "Se obtuvo la informacion del sitio externo de forma exitosa"
msgstr "A informação do site externo foi obtida com sucesso"

#: api_app/tests/tests_api_external_sites.py:108
#: api_app/views/external_site.py:165
msgid "Se elimino el sitio externo de forma exitosa"
msgstr "O site externo foi eliminado com sucesso"

#: api_app/tests/tests_api_external_sites.py:124
#: api_app/views/external_site.py:171
msgid "No está permitido eliminar un sitio externo asociado a una campaña"
msgstr "Não é permitido eliminar um site externo associado a uma campanha"

#: api_app/tests/tests_api_external_sites.py:140
#: api_app/views/external_site.py:199
msgid "Se oculto el sitio externo de forma exitosa"
msgstr "O site externo foi ocultado com sucesso"

#: api_app/tests/tests_api_external_sites.py:156
#: api_app/views/external_site.py:222
msgid "Se desoculto el sitio externo de forma exitosa"
msgstr "O site externo foi revelado com sucesso"

#: api_app/tests/tests_api_external_sites.py:181
#: api_app/views/external_site.py:70
msgid "Se creo el sitio externo de forma exitosa"
msgstr "O site externo foi criado com sucesso"

#: api_app/tests/tests_api_external_systems.py:58
#: api_app/views/external_system.py:44
msgid "Se obtuvieron los sistemas externos de forma exitosa"
msgstr "Os sistemas externos foram obtidos com sucesso"

#: api_app/tests/tests_api_external_systems.py:76
#: api_app/views/external_system.py:142
msgid "Se obtuvo la informacion del sistema externo de forma exitosa"
msgstr "A informação do sistema externo foi obtida com sucesso"

#: api_app/tests/tests_api_external_systems.py:105
#: api_app/views/external_system.py:72
msgid "Se creo el sistema externo de forma exitosa"
msgstr "O sistema externo foi criado com sucesso"

#: api_app/tests/tests_api_external_systems.py:136
#: api_app/views/external_system.py:103
msgid "Se actualizo el sistema externo de forma exitosa"
msgstr "O sistema externo foi atualizado com sucesso"

#: api_app/tests/tests_api_forms.py:109 api_app/views/form.py:43
msgid "Se obtuvieron los formularios de forma exitosa"
msgstr "Os formulários foram obtidos com sucesso"

#: api_app/tests/tests_api_forms.py:130 api_app/views/form.py:146
msgid "Se obtuvo la informacion del formulario de forma exitosa"
msgstr "A informação do formulário foi obtida com sucesso"

#: api_app/tests/tests_api_forms.py:146 api_app/views/form.py:70
msgid "Se creo el formulario de forma exitosa"
msgstr "O formulário foi criado com sucesso"

#: api_app/tests/tests_api_forms.py:162 api_app/views/form.py:177
msgid "Se elimino el formulario de forma exitosa"
msgstr "O formulário foi eliminado com sucesso"

#: api_app/tests/tests_api_forms.py:176 api_app/views/form.py:183
msgid "No está permitido eliminar un formulario con calificaciones"
msgstr "Não é permitido eliminar um formulário com qualificações"

#: api_app/tests/tests_api_forms.py:192 api_app/views/form.py:211
msgid "Se oculto el formulario de forma exitosa"
msgstr "O formulário foi ocultado com sucesso"

#: api_app/tests/tests_api_forms.py:208 api_app/views/form.py:234
msgid "Se desoculto el formulario de forma exitosa"
msgstr "O formulário foi revelado com sucesso"

#: api_app/tests/tests_api_forms.py:234 api_app/views/form.py:101
msgid "Se actualizo el formulario de forma exitosa"
msgstr "O formulário foi atualizado com sucesso"

#: api_app/tests/tests_api_forms.py:256 api_app/views/form.py:107
msgid "No está permitido actualizar un formulario con calificaciones"
msgstr "Não é permitido atualizar um formulário com qualificações"

#: api_app/tests/tests_api_group_of_hour.py:79
#: api_app/views/group_of_hour.py:47
msgid "Se obtuvieron los grupos horarios de forma exitosa"
msgstr "Os grupos horários foram obtidos com sucesso"

#: api_app/tests/tests_api_group_of_hour.py:97
#: api_app/views/group_of_hour.py:151
msgid "Se obtuvo la informacion el grupo horario de forma exitosa"
msgstr "A informação do grupo horário foi obtida com sucesso"

#: api_app/tests/tests_api_group_of_hour.py:116
#: api_app/views/group_of_hour.py:74
msgid "Se creo el grupo horario de forma exitosa"
msgstr "O grupo horário foi criado com sucesso"

#: api_app/tests/tests_api_group_of_hour.py:134
#: api_app/views/group_of_hour.py:181
msgid "Se elimino el grupo horario de forma exitosa"
msgstr "O grupo horário foi eliminado com sucesso"

#: api_app/tests/tests_api_group_of_hour.py:145
#: api_app/views/group_of_hour.py:187
msgid ""
"No está permitido eliminar un grupo horario asociado a Validacion Fecha Hora"
msgstr ""
"Não é permitido eliminar um grupo horário associado à Validação Data Hora"

#: api_app/tests/tests_api_group_of_hour.py:188
#: api_app/views/group_of_hour.py:109
msgid "Se actualizo el grupo horario de forma exitosa"
msgstr "O grupo horário foi atualizado com sucesso"

#: api_app/tests/tests_api_inbound_route.py:78
#: api_app/tests/tests_api_outbound_route.py:114
#: api_app/views/inbound_route.py:46 api_app/views/outbound_route.py:49
msgid "Se obtuvieron las rutas entrantes de forma exitosa"
msgstr "As rotas de entrada foram obtidas com sucesso"

#: api_app/tests/tests_api_inbound_route.py:105
#: api_app/views/inbound_route.py:151
msgid "Se obtuvo la informacion de la ruta entrante de forma exitosa"
msgstr "A informação da rota de entrada foi obtida com sucesso"

#: api_app/tests/tests_api_inbound_route.py:128
#: api_app/views/inbound_route.py:73
msgid "Se creo la ruta entrante de forma exitosa"
msgstr "A rota de entrada foi criada com sucesso"

#: api_app/tests/tests_api_inbound_route.py:147
#: api_app/views/inbound_route.py:182
msgid "Se elimino la ruta entrante de forma exitosa"
msgstr "A rota de entrada foi eliminada com sucesso"

#: api_app/tests/tests_api_inbound_route.py:193
#: api_app/views/inbound_route.py:107
msgid "Se actualizo la ruta entrante de forma exitosa"
msgstr "A rota de entrada foi atualizada com sucesso"

#: api_app/tests/tests_api_ivr.py:223 api_app/views/ivr.py:54
msgid "Se obtuvieron los IVRs de forma exitosa"
msgstr "Os IVRs foram obtidos com sucesso"

#: api_app/tests/tests_api_ivr.py:241 api_app/views/ivr.py:168
msgid "Se obtuvo la informacion del IVR de forma exitosa"
msgstr "A informação do IVR foi obtida com sucesso"

#: api_app/tests/tests_api_ivr.py:261 api_app/views/ivr.py:82
msgid "Se creo el IVR de forma exitosa"
msgstr "O IVR foi criado com sucesso"

#: api_app/tests/tests_api_ivr.py:294 api_app/views/ivr.py:211
msgid "Se elimino el IVR de forma exitosa"
msgstr "O IVR foi eliminado com sucesso"

#: api_app/tests/tests_api_ivr.py:306 api_app/tests/tests_api_ivr.py:326
#: api_app/views/ivr.py:197
msgid "No se puede eliminar un objeto que es destino en un flujo de llamada."
msgstr ""
"Não é possível eliminar um objeto que é destino em um fluxo de chamada."

#: api_app/tests/tests_api_outbound_route.py:138
#: api_app/views/outbound_route.py:152
msgid "Se obtuvo la informacion de la ruta saliente de forma exitosa"
msgstr "A informação da rota de saída foi obtida com sucesso"

#: api_app/tests/tests_api_outbound_route.py:160
#: api_app/views/outbound_route.py:76
msgid "Se creo la ruta saliente de forma exitosa"
msgstr "A rota de saída foi criada com sucesso"

#: api_app/tests/tests_api_outbound_route.py:181
#: api_app/views/outbound_route.py:184
msgid "Se elimino la ruta saliente de forma exitosa"
msgstr "A rota de saída foi eliminada com sucesso"

#: api_app/tests/tests_api_outbound_route.py:195
#: api_app/views/outbound_route.py:190
msgid "No está permitido eliminar una ruta saliente asociada a una campaña"
msgstr "Não é permitido eliminar uma rota de saída associada a uma campanha"

#: api_app/tests/tests_api_outbound_route.py:357
#: api_app/views/outbound_route.py:110
msgid "Se actualizo la ruta saliente de forma exitosa"
msgstr "A rota de saída foi atualizada com sucesso"

#: api_app/tests/tests_api_pauses.py:65 api_app/views/pause.py:66
#: api_app/views/pause_set.py:44
msgid "Se obtuvieron las pausas de forma exitosa"
msgstr "As pausas foram obtidas com sucesso"

#: api_app/tests/tests_api_pauses.py:83 api_app/views/pause.py:276
msgid "Se obtuvo la informacion de la pausa de forma exitosa"
msgstr "A informação da pausa foi obtida com sucesso"

#: api_app/tests/tests_api_pauses.py:103 api_app/views/pause.py:92
msgid "Se creo la pausa de forma exitosa"
msgstr "A pausa foi criada com sucesso"

#: api_app/tests/tests_api_pauses.py:124 api_app/views/pause.py:197
msgid "Se elimino la pausa de forma exitosa"
msgstr "A pausa foi eliminada com sucesso"

#: api_app/tests/tests_api_pauses.py:138 api_app/views/pause.py:203
msgid "No está permitido eliminar un pausa con configuraciones creadas"
msgstr "Não é permitido eliminar uma pausa com configurações criadas"

#: api_app/tests/tests_api_pauses.py:164 api_app/views/pause.py:140
msgid "Se actualizo la pausa de forma exitosa"
msgstr "A pausa foi atualizada com sucesso"

#: api_app/tests/tests_api_pauses.py:202 api_app/views/pause.py:240
msgid "Se reactivo la pausa de forma exitosa"
msgstr "A pausa foi reativada com sucesso"

#: api_app/tests/tests_api_permisos.py:55 api_app/views/administrador.py:82
msgid "Ya existe un rol con ese nombre"
msgstr "Já existe um papel com esse nome"

#: api_app/tests/tests_api_permisos.py:65 api_app/views/administrador.py:77
msgid "Se esperaba el campo \"name\""
msgstr "Era esperado o campo \"nome\""

#: api_app/tests/tests_api_permisos.py:97 api_app/views/administrador.py:107
msgid "Se esperaba el campo \"role_id\" (numérico)"
msgstr "Era esperado o campo \"role_id\" (numérico)"

#: api_app/tests/tests_api_permisos.py:104
#: api_app/tests/tests_api_permisos.py:112
#: api_app/tests/tests_api_permisos.py:172 api_app/views/administrador.py:114
#: api_app/views/administrador.py:144
msgid "Id de Rol incorrecto"
msgstr "Id de Papel incorreto"

#: api_app/tests/tests_api_permisos.py:121
#: api_app/tests/tests_api_permisos.py:130 api_app/views/administrador.py:118
msgid "Se esperaba el campo \"permissions\" (lista)"
msgstr "Era esperado o campo \"permissões\" (lista)"

#: api_app/tests/tests_api_permisos.py:140 api_app/views/administrador.py:123
msgid "Lista de permisos incorrecta"
msgstr "Lista de permissões incorreta"

#: api_app/tests/tests_api_permisos.py:163 api_app/views/administrador.py:149
msgid "No se puede borrar un rol asignado a usuarios."
msgstr "Não é possível apagar um papel atribuído a usuários."

#: api_app/tests/tests_api_register_server.py:55
#: api_app/views/register_server.py:42
msgid "Se obtuvo el registro del servidor forma exitosa"
msgstr "O registro do servidor foi obtido com sucesso"

#: api_app/tests/tests_api_register_server.py:82
#: api_app/views/register_server.py:77
msgid "Se creo el registro al servidor de forma exitosa"
msgstr "O registro no servidor foi criado com sucesso"

#: api_app/tests/tests_api_subir_base_contactos.py:105
#: api_app/views/administrador.py:191
msgid "falta parámetro filename en request"
msgstr "falta parâmetro filename no pedido"

#: api_app/tests/tests_api_subir_base_contactos.py:117
#: api_app/tests/tests_api_subir_base_contactos.py:129
#: api_app/views/administrador.py:213
msgid "falta parámetro:"
msgstr "falta parâmetro:"

#: api_app/tests/tests_api_subir_base_contactos.py:142
#: api_app/views/administrador.py:228
msgid "campo de teléfono no coincide con nombre de columna"
msgstr "campo de telefone não coincide com nome de coluna"

#: api_app/tests/tests_api_subir_base_contactos.py:155
#: api_app/views/administrador.py:236
msgid "campo de id externo no coincide con nombre de columna"
msgstr "campo de id externo não coincide com o nome da coluna"

#: api_app/tests/tests_api_subir_base_contactos.py:167
#: api_app/views/administrador.py:188
msgid "la extensión del archivo no es .CSV"
msgstr "a extensão do arquivo não é .CSV"

#: api_app/tests/tests_api_subir_base_contactos.py:181
#: api_app/views/administrador.py:184
#, python-brace-format
msgid "La longitud del nombre no debe exceder los {0} caracteres"
msgstr "O comprimento do nome não deve exceder {0} caracteres"

#: api_app/views/administrador.py:201
msgid "no se pudo crear la base de datos de contacto"
msgstr "não foi possível criar o banco de dados de contato"

#: api_app/views/administrador.py:225
msgid "lista de campos teléfono vacia"
msgstr "lista de campos de telefone vazia"

#: api_app/views/administrador.py:285
msgid "Error en el servidor externo"
msgstr "Erro no servidor externo"

#: api_app/views/agente.py:74
msgid "Error al generar sip password"
msgstr "Erro ao gerar senha sip"

#: api_app/views/agente.py:229 api_app/views/agente.py:264
#: api_app/views/base_de_contactos.py:80 api_app/views/base_de_contactos.py:212
msgid "Hubo errores en los datos recibidos"
msgstr "Houve erros nos dados recebidos"

#: api_app/views/agente.py:255
msgid "Error al ejecutar la llamada"
msgstr "Erro ao executar a chamada"

#: api_app/views/agente.py:285
msgid "Usted no tiene permiso para realizar esta acción"
msgstr "Você não tem permissão para realizar esta ação"

#: api_app/views/agente.py:298
msgid "Valor de destination inválido"
msgstr "Valor de destino inválido"

#: api_app/views/agente.py:308
msgid "Valor de destination_type inválido"
msgstr "Valor de destination_type inválido"

#: api_app/views/agente.py:312
msgid "Llamada fuera de campaña iniciada"
msgstr "Chamada fora da campanha iniciada"

#: api_app/views/agente.py:552
msgid "Auditoría inexistente"
msgstr "Auditoria inexistente"

#: api_app/views/agente.py:557
msgid "No tiene permiso para modificar la auditoría"
msgstr "Não tem permissão para modificar a auditoria"

#: api_app/views/audios_asterisk.py:42
msgid "Se obtuvieron los lenguajes de forma exitosa"
msgstr "Os idiomas foram obtidos com sucesso"

#: api_app/views/audios_asterisk.py:50
msgid "Error al obtener los lenguajes"
msgstr "Erro ao obter os idiomas"

#: api_app/views/auditoria.py:80
msgid "Fecha-Hora"
msgstr "Data-Hora"

#: api_app/views/auditoria.py:81
msgid "Agente"
msgstr "Agente"

#: api_app/views/auditoria.py:82
msgid "Contacto ID"
msgstr "ID do Contato"

#: api_app/views/auditoria.py:83
msgid "Telefono"
msgstr "Telefone"

#: api_app/views/auditoria.py:84
msgid "Status"
msgstr "Status"

#: api_app/views/auditoria.py:86
msgid "Calificado"
msgstr "Qualificado"

#: api_app/views/auditoria.py:87
msgid "Observaciones"
msgstr "Observações"

#: api_app/views/auditoria.py:102
msgid "Pendiente"
msgstr "Pendente"

#: api_app/views/auditoria.py:146
msgid "Exportación de auditoria a .csv en proceso"
msgstr "Exportação de auditoria para .csv em processo"

#: api_app/views/base_de_contactos.py:53
msgid ""
"Se obtuvieron las campanas asociadas a la base de contactos de forma exitosa"
msgstr "As campanhas associadas à base de contatos foram obtidas com sucesso"

#: api_app/views/base_de_contactos.py:67
msgid "Error al obtener las campañas asociadas a la base de datos de contactos"
msgstr "Erro ao obter as campanhas associadas à base de dados de contatos"

#: api_app/views/base_de_contactos.py:318
msgid "Debe ingresar una lista"
msgstr "Deve inserir uma lista"

#: api_app/views/base_de_contactos.py:320
msgid "Debe ingresar al menos un campo"
msgstr "Deve inserir pelo menos um campo"

#: api_app/views/base_de_contactos.py:342
msgid "Los nombres de los campos no pueden estar repetidos"
msgstr "Os nomes dos campos não podem estar repetidos"

#: api_app/views/base_de_contactos.py:388
msgid "Se creo la BD de Contactos de forma exitosa"
msgstr "O BD de Contatos foi criado com sucesso"

#: api_app/views/base_de_contactos.py:391
#: api_app/views/base_de_contactos.py:494
msgid "Error en los datos"
msgstr "Erro nos dados"

#: api_app/views/base_de_contactos.py:422
msgid "El id externo debe ser único en la base de datos - {}"
msgstr "O id externo deve ser único no banco de dados - {}"

#: api_app/views/base_de_contactos.py:441
msgid "campo requerido"
msgstr "campo requerido"

#: api_app/views/base_de_contactos.py:457
msgid "Campos invalidos: {}"
msgstr "Campos inválidos: {}"

#: api_app/views/base_de_contactos.py:481
#: api_app/views/base_de_contactos.py:508
msgid "Base de datos inexistente"
msgstr "Banco de dados inexistente"

#: api_app/views/base_de_contactos.py:491
msgid "Se crearon los contactos de forma exitosa"
msgstr "Os contatos foram criados com sucesso"

#: api_app/views/base_de_contactos.py:505
msgid "Se obtuvieron los contactos de forma exitosa"
msgstr "Os contatos foram obtidos com sucesso"

#: api_app/views/call_disposition.py:54
msgid "Error al obtener las calificaciones"
msgstr "Erro ao obter as qualificações"

#: api_app/views/call_disposition.py:69
msgid "Se obtuvo el detalle de la calificacion de forma exitosa"
msgstr "O detalhe da qualificação foi obtido com sucesso"

#: api_app/views/call_disposition.py:79 api_app/views/call_disposition.py:211
msgid "No existe la calificacion"
msgstr "A qualificação não existe"

#: api_app/views/call_disposition.py:84
msgid "Error al obtener el detalle de la calificacion"
msgstr "Erro ao obter o detalhe da qualificação"

#: api_app/views/call_disposition.py:127
msgid "Error al crear la calificacion"
msgstr "Erro ao criar a qualificação"

#: api_app/views/call_disposition.py:173
msgid "No existe la calificacion que se quiere actualizar"
msgstr "A qualificação que se deseja atualizar não existe"

#: api_app/views/call_disposition.py:179
msgid "Error al actualizar la calificacion"
msgstr "Erro ao atualizar a qualificação"

#: api_app/views/call_disposition.py:203
msgid "No está permitido eliminar una calificacion reservada del sistema"
msgstr "Não é permitido eliminar uma qualificação reservada do sistema"

#: api_app/views/call_disposition.py:216
msgid "Error al eliminar la calificacion"
msgstr "Erro ao eliminar a qualificação"

#: api_app/views/campaigns/add_agents_to_campaign.py:58
#: api_app/views/supervisor.py:464 api_app/views/supervisor.py:479
msgid "No existe la campaña"
msgstr "A campanha não existe"

#: api_app/views/campaigns/add_agents_to_campaign.py:99
msgid "No existe la campaña, no se pueden agregar agentes"
msgstr "A campanha não existe, não é possível adicionar agentes"

#: api_app/views/campaigns/add_agents_to_campaign.py:113
msgid "No existe el agente, no se puede eliminar de la member queue"
msgstr "O agente não existe, não pode ser removido da fila de membros"

#: api_app/views/campaigns/add_agents_to_campaign.py:119
msgid "No existe el agente, no se puede crear la member queue"
msgstr "O agente não existe, não é possível criar a fila de membros"

#: api_app/views/campaigns/add_agents_to_campaign.py:133
msgid "No se pudo confirmar la creación del dialplan"
msgstr "Não foi possível confirmar a criação do plano de discagem"

#: api_app/views/campaigns/add_agents_to_campaign.py:154
msgid "Asignación de agente a campañas actualizada"
msgstr "Atribuição de agente à campanha atualizada"

#: api_app/views/campaigns/add_agents_to_campaign.py:160
msgid "Parámetro \"agent_id\" requerido"
msgstr "Parâmetro \"agent_id\" requerido"

#: api_app/views/campaigns/add_agents_to_campaign.py:164
msgid "agent_id incorrecto"
msgstr "agent_id incorreto"

#: api_app/views/campaigns/add_agents_to_campaign.py:169
msgid "Parámetro \"campaigns\" de tipo \"list\" requerido"
msgstr "Parâmetro \"campaigns\" de tipo \"list\" requerido"

#: api_app/views/campaigns/add_agents_to_campaign.py:180
#, python-brace-format
msgid "IDs de campañas inválidas: {0}"
msgstr "IDs de campanhas inválidos: {0}"

#: api_app/views/campaigns/add_agents_to_campaign.py:205
msgid "Error asignando campañas. No se pudo confirmar la creación del dialplan"
msgstr ""
"Erro ao atribuir campanhas. Não foi possível confirmar a criação do plano de "
"discagem"

#: api_app/views/campaigns/add_agents_to_campaign.py:240
msgid "Error al obtener los agentes activos"
msgstr "Erro ao obter os agentes ativos"

#: api_app/views/external_site.py:53
msgid "Error al obtener los sitios externos"
msgstr "Erro ao obter os sites externos"

#: api_app/views/external_site.py:84
msgid "Error al crear el sitio externo"
msgstr "Erro ao criar o site externo"

#: api_app/views/external_site.py:101
msgid "Se actualizo el sitio externo de forma exitosa"
msgstr "O site externo foi atualizado com sucesso"

#: api_app/views/external_site.py:118
msgid "No existe el sitio externo que se quiere actualizar"
msgstr "O site externo que se deseja atualizar não existe"

#: api_app/views/external_site.py:124
msgid "Error al actualizar el sitio externo"
msgstr "Erro ao atualizar o site externo"

#: api_app/views/external_site.py:149
msgid "Error al obtener el detalle del sitio externo"
msgstr "Erro ao obter o detalhe do site externo"

#: api_app/views/external_site.py:179
msgid "No existe el sitio externo"
msgstr "O site externo não existe"

#: api_app/views/external_site.py:184
msgid "Error al eliminar el sitio externo"
msgstr "Erro ao eliminar o site externo"

#: api_app/views/external_site.py:207
msgid "Error al ocultar el sitio externo"
msgstr "Erro ao ocultar o site externo"

#: api_app/views/external_site.py:230
msgid "Error al desocultar el sitio externo"
msgstr "Erro ao revelar o site externo"

#: api_app/views/external_site_authentication.py:56
msgid "Error al obtener las autenticaciones para sitios externos"
msgstr "Erro ao obter as autenticações para sites externos"

#: api_app/views/external_site_authentication.py:88
msgid "Error al crear la autenticacion para sitio externo"
msgstr "Erro ao criar a autenticação para site externo"

#: api_app/views/external_site_authentication.py:111
msgid "Autenticación Satisfactoria a CRM"
msgstr "Autenticação com CRM correta"

#: api_app/views/external_site_authentication.py:127
msgid "Autenticación Fallida a CRM: <{}>"
msgstr "Autenticação com CRM falida"

#: api_app/views/external_site_authentication.py:142
msgid "Se actualizo la autenticacion para sitio externo de forma exitosa"
msgstr "A autenticação para o site externo foi atualizada com sucesso"

#: api_app/views/external_site_authentication.py:160
msgid "No existe la autenticacion para sitio externo que se quiere actualizar"
msgstr "Não existe a autenticação para o site externo que se deseja atualizar"

#: api_app/views/external_site_authentication.py:166
msgid "Error al actualizar la autenticacion para sitio externo"
msgstr "Erro ao atualizar a autenticação para o site externo"

#: api_app/views/external_site_authentication.py:192
msgid "Error al obtener el detalle de la autenticacion para sitio externo"
msgstr "Erro ao obter o detalhe da autenticação para o site externo"

#: api_app/views/external_site_authentication.py:222
msgid "No existe la autenticacion para sitio externo"
msgstr "A autenticação para o site externo não existe"

#: api_app/views/external_site_authentication.py:227
msgid "Error al eliminar la autenticacion para sitio externo"
msgstr "Erro ao eliminar a autenticação para o site externo"

#: api_app/views/external_system.py:55
msgid "Error al obtener los sistemas externos"
msgstr "Erro ao obter os sistemas externos"

#: api_app/views/external_system.py:86
msgid "Error al crear el sistema externo"
msgstr "Erro ao criar o sistema externo"

#: api_app/views/external_system.py:120
msgid "No existe el sistema externo que se quiere actualizar"
msgstr "O sistema externo que se deseja atualizar não existe"

#: api_app/views/external_system.py:126
msgid "Error al actualizar el sistema externo"
msgstr "Erro ao atualizar o sistema externo"

#: api_app/views/external_system.py:151
msgid "No existe el sistema externo para obtener el detalle"
msgstr "O sistema externo para obter o detalhe não existe"

#: api_app/views/external_system.py:157
msgid "Error al obtener el detalle del sistema externo"
msgstr "Erro ao obter o detalhe do sistema externo"

#: api_app/views/external_system.py:183
msgid "Error al obtener los agentes"
msgstr "Erro ao obter os agentes"

#: api_app/views/form.py:53
msgid "Error al obtener los formularios"
msgstr "Erro ao obter os formulários"

#: api_app/views/form.py:84
msgid "Error al crear el formulario"
msgstr "Erro ao criar o formulário"

#: api_app/views/form.py:124
msgid "No existe el formulario que se quiere actualizar"
msgstr "O formulário que se deseja atualizar não existe"

#: api_app/views/form.py:130
msgid "Error al actualizar el formulario"
msgstr "Erro ao atualizar o formulário"

#: api_app/views/form.py:155
msgid "No existe el formulario para obtener el detalle"
msgstr "O formulário para obter o detalhe não existe"

#: api_app/views/form.py:161
msgid "Error al obtener el detalle del formulario"
msgstr "Erro ao obter o detalhe do formulário"

#: api_app/views/form.py:191
msgid "No existe el formulario"
msgstr "O formulário não existe"

#: api_app/views/form.py:196
msgid "Error al eliminar el formulario"
msgstr "Erro ao eliminar o formulário"

#: api_app/views/form.py:219
msgid "Error al ocultar el formulario"
msgstr "Erro ao ocultar o formulário"

#: api_app/views/form.py:242
msgid "Error al desocultar el formulario"
msgstr "Erro ao revelar o formulário"

#: api_app/views/grabaciones.py:94
msgid "Exportación de grabaciones Zip en proceso"
msgstr "Exportação de gravações Zip em andamento"

#: api_app/views/group_of_hour.py:57
msgid "Error al obtener los grupos horarios"
msgstr "Erro ao obter os grupos horários"

#: api_app/views/group_of_hour.py:80
msgid ""
"Se creo el grupo horario pero no se pudo cargar la configuración telefónica"
msgstr ""
"O grupo horário foi criado, mas a configuração telefônica não pôde ser "
"carregada"

#: api_app/views/group_of_hour.py:92
msgid "Error al crear el grupo horario"
msgstr "Erro ao criar o grupo horário"

#: api_app/views/group_of_hour.py:118
msgid ""
"Se actualizo el grupo horario pero no se pudo cargar la configuración "
"telefónica"
msgstr ""
"O grupo horário foi atualizado, mas a configuração telefônica não pôde ser "
"carregada"

#: api_app/views/group_of_hour.py:135
msgid "Error al actualizar el grupo horario"
msgstr "Erro ao atualizar o grupo horário"

#: api_app/views/group_of_hour.py:165
msgid "Error al obtener el detalle del grupo horario"
msgstr "Erro ao obter o detalhe do grupo horário"

#: api_app/views/group_of_hour.py:192
msgid ""
"Se elimino el grupo horario pero no se pudo cargar la configuración "
"telefónica"
msgstr ""
"O grupo horário foi eliminado, mas a configuração telefônica não pôde ser "
"carregada"

#: api_app/views/group_of_hour.py:208
msgid "Grupo Horario"
msgstr "Grupo Horário"

#: api_app/views/group_of_hour.py:206
#, python-brace-format
msgid ""
"No está permitido eliminar el '{modelo}' porque está siendo usado por "
"{related}."
msgstr ""
"Não é permitido eliminar o '{modelo}' porque esta sendo utilizado por "
"{related}."

#: api_app/views/inbound_route.py:56
msgid "Error al obtener las rutas entrantes"
msgstr "Erro ao obter as rotas de entrada"

#: api_app/views/inbound_route.py:79
msgid ""
"Se creo la ruta entrante pero no se pudo cargar la configuración telefónica"
msgstr ""
"A rota de entrada foi criada, mas a configuração telefônica não pôde ser "
"carregada"

#: api_app/views/inbound_route.py:90
msgid "Error al crear la ruta entrante"
msgstr "Erro ao criar a rota de entrada"

#: api_app/views/inbound_route.py:118 api_app/views/inbound_route.py:195
msgid ""
"Se actualizo la ruta entrante pero no se pudo cargar la configuración "
"telefónica"
msgstr ""
"A rota de entrada foi atualizada, mas a configuração telefônica não pôde ser "
"carregada"

#: api_app/views/inbound_route.py:129
msgid "No existe la ruta entrante que se quiere actualizar"
msgstr "A rota de entrada que se deseja atualizar não existe"

#: api_app/views/inbound_route.py:135
msgid "Error al actualizar la ruta entrante"
msgstr "Erro ao atualizar a rota de entrada"

#: api_app/views/inbound_route.py:160
msgid "No existe la ruta entrante para obtener el detalle"
msgstr "A rota de entrada para obter detalhes não existe"

#: api_app/views/inbound_route.py:166
msgid "Error al obtener el detalle de la ruta entrante"
msgstr "Erro ao obter detalhes da rota de entrada"

#: api_app/views/inbound_route.py:189
msgid ""
"No está permitido eliminar una Ruta Entrante asociada con una campaña que "
"tiene una Ruta Saliente."
msgstr ""
"Não é permitido eliminar uma Rota de Entrada associada a uma campanha que "
"tem uma Rota de Saída."

#: api_app/views/inbound_route.py:201
msgid "No existe la ruta entrante"
msgstr "A rota de entrada não existe"

#: api_app/views/inbound_route.py:206
msgid "Error al eliminar la ruta entrante"
msgstr "Erro ao eliminar a rota de entrada"

#: api_app/views/inbound_route.py:221
msgid "Se obtuvo la informacion de los destinos de forma exitosa"
msgstr "As informações dos destinos foram obtidas com sucesso"

#: api_app/views/inbound_route.py:241
msgid "Error al obtener los destinos de las rutas entrantes"
msgstr "Erro ao obter os destinos das rotas de entrada"

#: api_app/views/ivr.py:60
msgid "Error al obtener los ivrs"
msgstr "Erro ao obter os IVRs"

#: api_app/views/ivr.py:84
msgid "Se creo el IVR pero no se pudo cargar la configuración telefónica"
msgstr "O IVR foi criado, mas a configuração telefônica não pôde ser carregada"

#: api_app/views/ivr.py:95 api_app/views/ivr.py:140 api_app/views/ivr.py:208
msgid "Error en los datos enviados"
msgstr "Erro nos dados enviados"

#: api_app/views/ivr.py:101
msgid "Error al crear el IVR"
msgstr "Erro ao criar o IVR"

#: api_app/views/ivr.py:124
msgid "Se actualizo el IVR de forma exitosa"
msgstr "O IVR foi atualizado com sucesso"

#: api_app/views/ivr.py:129
msgid "Se actualizo el IVR pero no se pudo cargar la configuración telefónica"
msgstr ""
"O IVR foi atualizado, mas a configuração telefônica não pôde ser carregada"

#: api_app/views/ivr.py:146 api_app/views/ivr.py:174 api_app/views/ivr.py:225
msgid "No existe el IVR"
msgstr "O IVR não existe"

#: api_app/views/ivr.py:151
msgid "Error al actualizar el IVR"
msgstr "Erro ao atualizar o IVR"

#: api_app/views/ivr.py:179
msgid "Error al obtener el detalle del IVR"
msgstr "Erro ao obter detalhes do IVR"

#: api_app/views/ivr.py:202
#, python-brace-format
msgid ""
"No se puede eliminar la campaña.Es usada como destino failover de las "
"campañas: {0}"
msgstr ""
"Não é possível eliminar a campanha. Ela é usada como destino de failover das "
"campanhas: {0}"

#: api_app/views/ivr.py:213
msgid "Se elimino el IVR pero no se pudo cargar la configuración telefónica"
msgstr ""
"O IVR foi eliminado, mas a configuração telefônica não pôde ser carregada"

#: api_app/views/ivr.py:230
msgid "Error al eliminar el IVR"
msgstr "Erro ao eliminar o IVR"

#: api_app/views/ivr.py:249
msgid "Se obtuvieron los archivos de audio de forma exitosa"
msgstr "Os arquivos de áudio foram obtidos com sucesso"

#: api_app/views/ivr.py:255
msgid "Error al obtener los archivos de audio"
msgstr "Erro ao obter os arquivos de áudio"

#: api_app/views/ivr.py:284
msgid "Se obtuvieron los destinos de forma exitosa"
msgstr "Os destinos foram obtidos com sucesso"

#: api_app/views/ivr.py:290
msgid "Error al obtener los destinos"
msgstr "Erro ao obter os destinos"

#: api_app/views/logging.py:44
msgid "Se creo el Log de transferencia a Encuesta"
msgstr "O Log de transferência para Pesquisa foi criado"

#: api_app/views/logging.py:63
msgid "Error al crear el Log de transferencia"
msgstr "Erro ao criar o Log de transferência"

#: api_app/views/outbound_route.py:59
msgid "Error al obtener las rutas salientes"
msgstr "Erro ao obter as rotas de saída"

#: api_app/views/outbound_route.py:82
msgid ""
"Se creo la ruta saliente pero no se pudo cargar la configuración telefónica"
msgstr ""
"A rota de saída foi criada, mas a configuração telefônica não pôde ser "
"carregada"

#: api_app/views/outbound_route.py:93
msgid "Error al crear la ruta saliente"
msgstr "Erro ao criar a rota de saída"

#: api_app/views/outbound_route.py:119
msgid ""
"Se actualizo la ruta saliente pero no se pudo cargar la configuración "
"telefónica"
msgstr ""
"A rota de saída foi atualizada, mas a configuração telefônica não pôde ser "
"carregada"

#: api_app/views/outbound_route.py:130
msgid "No existe la ruta saliente que se quiere actualizar"
msgstr "A rota de saída que se deseja atualizar não existe"

#: api_app/views/outbound_route.py:136
msgid "Error al actualizar la ruta saliente"
msgstr "Erro ao atualizar a rota de saída"

#: api_app/views/outbound_route.py:162
msgid "No existe la ruta saliente para obtener el detalle"
msgstr "A rota de saída para obter detalhes não existe"

#: api_app/views/outbound_route.py:168
msgid "Error al obtener el detalle de la ruta saliente"
msgstr "Erro ao obter detalhes da rota de saída"

#: api_app/views/outbound_route.py:195
msgid "Se elimino la ruta pero no se pudo cargar la configuración telefónica"
msgstr ""
"A rota foi eliminada, mas a configuração telefônica não pôde ser carregada"

#: api_app/views/outbound_route.py:201 api_app/views/outbound_route.py:261
msgid "No existe la ruta saliente"
msgstr "A rota de saída não existe"

#: api_app/views/outbound_route.py:206
msgid "Error al eliminar la ruta saliente"
msgstr "Erro ao eliminar a rota de saída"

#: api_app/views/outbound_route.py:221
msgid "Se obtuvieron las troncales sip de forma exitosa"
msgstr "As troncais SIP foram obtidas com sucesso"

#: api_app/views/outbound_route.py:231
msgid "Error al obtener las troncales"
msgstr "Erro ao obter as troncais"

#: api_app/views/outbound_route.py:246
msgid ""
"Se obtuvieron las troncales huerfanas de la ruta saliente de forma exitosa"
msgstr "As troncais órfãs da rota de saída foram obtidas com sucesso"

#: api_app/views/outbound_route.py:266
msgid "Error al obtener las troncales huerfanas de la ruta saliente"
msgstr "Erro ao obter as troncais órfãs da rota de saída"

#: api_app/views/outbound_route.py:281
msgid "El orden de las rutas salientes se actualizo de forma exitosa"
msgstr "A ordem das rotas de saída foi atualizada com sucesso"

#: api_app/views/outbound_route.py:287
msgid "El orden es un campo requerido"
msgstr "A ordem é um campo obrigatório"

#: api_app/views/outbound_route.py:292 api_app/views/outbound_route.py:297
msgid "El orden debe ser una lista de numeros enteros"
msgstr "A ordem deve ser uma lista de números inteiros"

#: api_app/views/outbound_route.py:302
msgid "El nuevo orden no coincide con la cantidad de rutas saliente"
msgstr "A nova ordem não coincide com a quantidade de rotas de saída"

#: api_app/views/outbound_route.py:309
msgid "No puede haber orden repetido en las rutas salientes"
msgstr "Não pode haver ordem repetida nas rotas de saída"

#: api_app/views/outbound_route.py:331
msgid "Error al actualizar el orden de las rutas salientes"
msgstr "Erro ao atualizar a ordem das rotas de saída"

#: api_app/views/pause.py:76 api_app/views/pause_set.py:54
msgid "Error al obtener las pausas"
msgstr "Erro ao obter as pausas"

#: api_app/views/pause.py:106 api_app/views/pause.py:157
#: api_app/views/pause.py:214 api_app/views/pause.py:250
msgid "Error al sincronizar la pausa con asterisk"
msgstr "Erro ao sincronizar a pausa com asterisco"

#: api_app/views/pause.py:123
msgid "Error al crear la pausa"
msgstr "Erro ao criar a pausa"

#: api_app/views/pause.py:181
msgid "Error al actualizar la pausa"
msgstr "Erro ao atualizar a pausa"

#: api_app/views/pause.py:225
msgid "Error al eliminar la pausa"
msgstr "Erro ao eliminar a pausa"

#: api_app/views/pause.py:261
msgid "Error al reactivar la pausa"
msgstr "Erro ao reativar a pausa"

#: api_app/views/pause.py:291
msgid "Error al obtener el detalle de la pausa"
msgstr "Erro ao obter detalhes da pausa"

#: api_app/views/pause_set.py:80
msgid "Error al obtener los conjuntos de pausas"
msgstr "Erro ao obter os conjuntos de pausas"

#: api_app/views/pause_set.py:95
msgid "Se obtuvo la informacion del conjunto de pausa de forma exitosa"
msgstr "As informações do conjunto de pausas foram obtidas com sucesso"

#: api_app/views/pause_set.py:112
msgid "Error al obtener el detalle del conjunto de pausa"
msgstr "Erro ao obter detalhes do conjunto de pausas"

#: api_app/views/pause_set.py:150
msgid "Error al crear el conjunto de pausa"
msgstr "Erro ao criar o conjunto de pausas"

#: api_app/views/pause_set.py:178 api_app/views/pause_set.py:212
#: api_app/views/pause_set.py:254
msgid "No existe el conjunto de pausa"
msgstr "O conjunto de pausas não existe"

#: api_app/views/pause_set.py:183
msgid "Error al actualizar el conjunto de pausa"
msgstr "Erro ao atualizar o conjunto de pausas"

#: api_app/views/pause_set.py:217
msgid "Error al eliminar el conjunto de pausa"
msgstr "Erro ao eliminar o conjunto de pausas"

#: api_app/views/pause_set.py:246
msgid "No existe la pausa"
msgstr "A pausa não existe"

#: api_app/views/pause_set.py:264
msgid "Error al crear la configuracion de pausa"
msgstr "Erro ao criar a configuração de pausa"

#: api_app/views/pause_set.py:292 api_app/views/pause_set.py:322
msgid "No existe la configuracion de pausa"
msgstr "A configuração de pausa não existe"

#: api_app/views/pause_set.py:297
msgid "Error al eliminar la configuracion de pausa"
msgstr "Erro ao eliminar a configuração de pausa"

#: api_app/views/pause_set.py:327
msgid "Error al actualizar la configuracion de pausa"
msgstr "Erro ao atualizar a configuração de pausa"

#: api_app/views/register_server.py:61
msgid "Error al obtener el registro al servidor"
msgstr "Erro ao obter o registro do servidor"

#: api_app/views/register_server.py:91
msgid "Falta informacion para completar el registro"
msgstr "Faltam informações para completar o registro"

#: api_app/views/register_server.py:97
msgid "Error al crear el registro al servidor"
msgstr "Erro ao criar o registro no servidor"

#: api_app/views/supervisor.py:107 api_app/views/supervisor.py:111
#: api_app/views/supervisor.py:114
msgid "Filtro \"type\" inválido"
msgstr "Filtro \"tipo\" inválido"

#: api_app/views/supervisor.py:123
msgid "Filtro \"agent\" inválido"
msgstr "Filtro \"agente\" inválido"

#: api_app/views/supervisor.py:127
msgid "Agente inexistente"
msgstr "Agente inexistente"

#: api_app/views/supervisor.py:138 api_app/views/supervisor.py:143
#: api_app/views/supervisor.py:146
msgid "Filtro \"status\" inválido"
msgstr "Filtro \"status\" inválido"

#: api_app/views/supervisor.py:357 api_app/views/supervisor.py:403
msgid "ID Agenda incorrecto"
msgstr "ID de Agenda incorreto"

#: api_app/views/supervisor.py:364
msgid "ID Agente incorrecto"
msgstr "ID de Agente incorreto"

#: api_app/views/supervisor.py:372 api_app/views/supervisor.py:410
msgid "No tiene permiso para editar esta Agenda"
msgstr "Não tem permissão para editar esta Agenda"

#: api_app/views/supervisor.py:429
msgid "Recibidas"
msgstr "Recebidas"

#: api_app/views/supervisor.py:430
msgid "Efectuadas"
msgstr "Realizadas"

#: api_app/views/supervisor.py:431
msgid "Atendidas"
msgstr "Atendidas"

#: api_app/views/supervisor.py:432
msgid "Conectadas"
msgstr "Conectadas"

#: api_app/views/supervisor.py:433
msgid "No Conectadas"
msgstr "Não Conectadas"

#: api_app/views/supervisor.py:434
msgid "Abandonadas"
msgstr "Abandonadas"

#: api_app/views/supervisor.py:435
msgid "Expiradas"
msgstr "Expiradas"

#: api_app/views/supervisor.py:436
msgid "Tiempo de Espera de Conexión(prom.)"
msgstr "Tempo de Espera de Conexão (média)"

#: api_app/views/supervisor.py:437
msgid "Tiempo de Espera de Atención(prom.)"
msgstr "Tempo de Espera de Atendimento (média)"

#: api_app/views/supervisor.py:438
msgid "Tiempo de Abandono(prom.)"
msgstr "Tempo de Abandono (média)"

#: api_app/views/supervisor.py:441
msgid "Efectuadas Manuales"
msgstr "Realizadas Manualmente"

#: api_app/views/supervisor.py:442
msgid "Conectadas Manuales"
msgstr "Conectadas Manualmente"

#: api_app/views/supervisor.py:443
msgid "No Conectadas Manuales"
msgstr "Não Conectadas Manualmente"

#: api_app/views/supervisor.py:444
msgid "Tiempo de Espera de Conexión Manuales(prom.)"
msgstr "Tempo de Espera de Conexão Manual (média)"

#: api_app/views/supervisor.py:570
msgid "Exportación de CSV en proceso"
msgstr "Exportação de CSV em processo"

#: api_app/views/supervisor.py:618
msgid "Exportación de contactados a .csv en proceso"
msgstr "Exportação de contactados para .csv em processo"

#: api_app/views/supervisor.py:665
msgid "Exportación de calificados a .csv en proceso"
msgstr "Exportação de qualificados para .csv em processo"

#: api_app/views/supervisor.py:712
msgid "Exportación de no atendidos a .csv en proceso"
msgstr "Exportação de não atendidos para .csv em processo"

#: api_app/views/supervisor.py:724
msgid "Finalizado"
msgstr "Finalizado"

#: api_app/views/supervisor.py:726
msgid "Liberado"
msgstr "Liberado"

#: api_app/views/supervisor.py:728
msgid "Reservado"
msgstr "Reservado"

#: api_app/views/supervisor.py:815
msgid "Exportación de calificaciones a .csv en proceso"
msgstr "Exportação de qualificações para .csv em processo"

#: api_app/views/supervisor.py:860
msgid "Exportación de Formularios de Gestiones a .csv en proceso"
msgstr "Exportação de Formulários de Gestão para .csv em processo"

#: api_app/views/wombat_dialer.py:48 api_app/views/wombat_dialer.py:91
msgid "Refrescando. Espere al menos 15 segundos mientras finaliza el proceso."
msgstr ""
"Atualizando. Aguarde pelo menos 15 segundos enquanto o processo é finalizado."

#: utiles_globales.py:35
msgid "Archivos permitidos: .wav"
msgstr "Arquivos permitidos: .wav"
